import os
import gnupg


def create(path):
    os.makedirs(path)


def key_input(passphrase):
    return gnupg.GPG().gen_key_input(
        name_real="Pysswords",
        name_email="pysswords@pysswords",
        name_comment="Auto-generated by Pysswords",
        key_length=4096,
        expire_date=0,
        passphrase=passphrase
    )


def create_keys(path, passphrase):
    gpg = gnupg.GPG(homedir=path)
    key = gpg.gen_key(key_input(passphrase))
    return key


def create_keyring(path, passphrase):
    gnupg.GPG(homedir=path)
    create_keys(path, passphrase)
