from collections import namedtuple
import os
import gnupg
import yaml

from .utils import which

Credential = namedtuple("Credential", "name login password comment")


def keys_path(path):
    return os.path.join(path, ".keys")


def getgpg(path):
    return gnupg.GPG(binary=which("gpg"), homedir=keys_path(path))


def pyssword_content(credential):
    return yaml.dump(credential)


def key_input(path, passphrase):
    return getgpg(path).gen_key_input(
        name_real="Pysswords",
        name_email="pysswords@pysswords",
        name_comment="Auto-generated by Pysswords",
        key_length=4096,
        expire_date=0,
        passphrase=passphrase
    )


def create_keys(path, passphrase):
    key = getgpg.gen_key(key_input(path, passphrase))
    return key


def create_keyring(path, passphrase):
    create_keys(keys_path(path), passphrase)
    return keys_path


def add_credential(path, credential):
    credential_dir = os.path.join(path, credential.name)
    os.makedirs(credential_dir)
    credential_file = "{}.pyssword".format(credential.login)
    with open(os.path.join(credential_dir, credential_file), "w") as f:
        f.write(pyssword_content(credential))


def create(path):
    os.makedirs(path)
