name: Tests python 3.10
on:
  workflow_call:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests-with-coverage-3-10:
    name: Run Python Tests with coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: '**/setup.py'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -e . -r requirements/tests.txt
      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=term --cov-report=xml:coverage.xml --color=yes
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.xml

  tests-with-coverage-3-2:
    name: Run Python Tests with coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python 3.2
        uses: actions/setup-python@v5
        with:
          python-version: "3.2"
          cache: "pip"
          cache-dependency-path: '**/setup.py'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -e . -r requirements/tests.txt
      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=term --cov-report=xml:coverage.xml --color=yes
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.xml

  tests-with-coverage-2-7:
    name: Run Python Tests with coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python 2.7
        uses: actions/setup-python@v5
        with:
          python-version: "2.7"
          cache: "pip"
          cache-dependency-path: '**/setup.py'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -e . -r requirements/tests.txt
      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=term --cov-report=xml:coverage.xml --color=yes
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.xml
